import one from '../../assets/img/clothes/w/one.jpeg';
import two from '../../assets/img/clothes/w/two.jpeg';
import three from '../../assets/img/clothes/w/three.jpeg';
import four from '../../assets/img/clothes/w/four.jpeg';
import five from '../../assets/img/clothes/w/five.jpeg';
import six from '../../assets/img/clothes/w/six.jpeg';
import seven from '../../assets/img/clothes/w/seven.jpeg';
import eight from '../../assets/img/clothes/w/8.jpeg';
import nine from '../../assets/img/clothes/w/9.jpeg';
import eleven from '../../assets/img/clothes/w/11.jpeg';
import twelve from '../../assets/img/clothes/w/12.jpeg';
import thirteen from '../../assets/img/clothes/w/13.jpeg';
import fourteen from '../../assets/img/clothes/w/14.jpeg';
import fifteen from '../../assets/img/clothes/w/15.jpeg';
import sixteen from '../../assets/img/clothes/w/16.jpeg';
import seventeen from '../../assets/img/clothes/w/17.jpeg';
import eighteen from '../../assets/img/clothes/w/18.jpeg';
import nineteen from '../../assets/img/clothes/w/19.jpeg';
import mOne from '../../assets/img/clothes/m/jean paul gaultier shirt.jpeg';
import mTwo from '../../assets/img/clothes/m/Alexander McQueen Fall 2016.jpeg';
import mThree from '../../assets/img/clothes/m/balenciaga light shoes.jpeg';
import mFour from '../../assets/img/clothes/m/Burberry Spring 2019.jpeg';
import mFive from '../../assets/img/clothes/m/Dolce & Gabbana Fall 2015.jpeg';
import mSix from '../../assets/img/clothes/m/Dries Van Noten Fall 2016.jpeg';
import mSeven from '../../assets/img/clothes/m/Gucci AW15.jpeg';
import mEight from '../../assets/img/clothes/m/nike shoes.jpeg';
import mNine from '../../assets/img/clothes/m/raf coat.jpeg';
import mTen from '../../assets/img/clothes/m/Raf Simons Men’s Fall 2018.jpeg';
import mEleven from '../../assets/img/clothes/m/Raf Simons Spring 2015.jpeg';
import mTwelve from '../../assets/img/clothes/m/UNDERCOVER 2016.jpeg';
import mThirteen from '../../assets/img/clothes/m/undercover backpack.jpeg';
import mFourteen from '../../assets/img/clothes/m/UNDERCOVER2020.jpeg';
import mFifteen from '../../assets/img/clothes/m/Yohji Yamamoto Spring 2018.jpeg';

const cards = [
  {
    title: 'Black Snake Dress',
    src: one,
    price: '1849.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Black',
    brand: 'Gucci',
    gender: 'women',
    key: '1',
  },
  {
    title: 'Tattered Silk Coat',
    src: two,
    price: '1379.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Grey',
    brand: 'Maison Margiela',
    gender: 'women',
    key: '2',
  },
  {
    title: 'Royal Gold Gown',
    src: three,
    price: '859.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Blue',
    brand: 'Luisa Beccaria',
    gender: 'women',
    key: '3',
  },
  {
    title: 'Fine Ripped Shirt',
    src: four,
    price: '1319.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Black',
    brand: 'Maison Margiela',
    gender: 'women',
    key: '4',
  },
  {
    title: 'Renaissance Dress',
    src: five,
    price: '2899.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'White',
    brand: 'Simone Rocha',
    gender: 'women',
    key: '5',
  },
  {
    title: 'Black Buttoned Overcoat',
    src: six,
    price: '659.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Black',
    brand: 'Yohji Yamamoto',
    gender: 'women',
    key: '6',
  },
  {
    title: 'Black Layered Top',
    src: seven,
    price: '779.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Black',
    brand: 'Anne Sofie Madsen',
    gender: 'women',
    key: '7',
  },
  {
    title: 'White Bracelet Sneakers',
    src: eight,
    price: '579.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Shoes',
    color: 'White',
    brand: 'Comme De Garcons',
    gender: 'women',
    key: '8',
  },
  {
    title: 'Gold and Black Heels',
    src: nine,
    price: '739.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Shoes',
    color: 'Gold',
    brand: 'Dolce & Gabbana',
    gender: 'women',
    key: '9',
  },

  {
    title: 'Gold and Pink Floral Heels',
    src: eleven,
    price: '1239.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Shoes',
    color: 'Gold',
    brand: 'Dolce & Gabbana',
    gender: 'women',
    key: '10',
  },
  {
    title: 'Stitched Mouse Top',
    src: twelve,
    price: '669.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'White',
    brand: 'Dolce & Gabbana',
    gender: 'women',
    key: '11',
  },
  {
    title: 'Black Emblem Bag',
    src: thirteen,
    price: '279.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Accessories',
    color: 'Black',
    brand: 'Jean Paul Gaultier',
    gender: 'women',
    key: '12',
  },
  {
    title: 'Glitter Skull Bag',
    src: fourteen,
    price: '339.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Accessories',
    color: 'Blue',
    brand: 'Manish Arora',
    gender: 'women',
    key: '13',
  },
  {
    title: 'Portrait Bag',
    src: fifteen,
    price: '489.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Accessories',
    color: 'Gold',
    brand: 'Moschino',
    gender: 'women',
    key: '14',
  },
  {
    title: 'Gold Bow Heels',
    src: sixteen,
    price: '1239.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Shoes',
    color: 'Gold',
    brand: 'Versace',
    gender: 'women',
    key: '15',
  },
  {
    title: 'Black Lace Dress',
    src: seventeen,
    price: '2579.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Black',
    brand: 'Valentino',
    gender: 'women',
    key: '16',
  },
  {
    title: 'Aged Snake Bag',
    src: eighteen,
    price: '899.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Accessories',
    color: 'Gold',
    brand: 'Valentino',
    gender: 'women',
    key: '17',
  },
  {
    title: 'Transparent Stitched Dress',
    src: nineteen,
    price: '1529.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Gold',
    brand: 'Valentino',
    gender: 'women',
    key: '18',
  },
  {
    title: 'Red Faces Shirt',
    src: mOne,
    price: '2529.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Red',
    brand: 'Jean Paul Gaultier',
    gender: 'men',
    key: '19',
  },
  {
    title: 'Butterfly Suit',
    src: mTwo,
    price: '979.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Black',
    brand: 'Alexander McQueen',
    gender: 'men',
    key: '20',
  },
  {
    title: 'Balenciaga Boots',
    src: mThree,
    price: '779.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Shoes',
    color: 'Black',
    brand: 'Balenciaga',
    gender: 'men',
    key: '21',
  },
  {
    title: 'Burberry Jacket',
    src: mFour,
    price: '779.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Brown',
    brand: 'Burberry',
    gender: 'men',
    key: '22',
  },
  {
    title: 'Gold Leaf Jacket',
    src: mFive,
    price: '3779.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Gold',
    brand: 'Dolce & Gabbana',
    gender: 'men',
    key: '23',
  },
  {
    title: 'Snake Coat',
    src: mSix,
    price: '3779.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Blue',
    brand: 'Dries Van Noten',
    gender: 'men',
    key: '24',
  },
  {
    title: 'Bee Pin',
    src: mSeven,
    price: '279.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Accessories',
    color: 'Gold',
    brand: 'Gucci',
    gender: 'men',
    key: '25',
  },
  {
    title: 'React Shoes',
    src: mEight,
    price: '349.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Shoes',
    color: 'Red',
    brand: 'Nike',
    gender: 'men',
    key: '26',
  },
  {
    title: 'Portrait Jacket',
    src: mNine,
    price: '6349.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Black',
    brand: 'Raf Simons',
    gender: 'men',
    key: '27',
  },
  {
    title: 'Red Girl Shirt',
    src: mTen,
    price: '1349.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Red',
    brand: 'Raf Simons',
    gender: 'men',
    key: '28',
  },
  {
    title: 'RS Pink Jacket',
    src: mEleven,
    price: '1149.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Red',
    brand: 'Raf Simons',
    gender: 'men',
    key: '29',
  },
  {
    title: 'Playing Card Pants',
    src: mTwelve,
    price: '949.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Bottom',
    color: 'Black',
    brand: 'Undercover',
    gender: 'men',
    key: '30',
  },
  {
    title: 'Castle Backpack',
    src: mThirteen,
    price: '699.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Accessories',
    color: 'Grey',
    brand: 'Undercover',
    gender: 'men',
    key: '31',
  },
  {
    title: 'Black Portrait Jacket',
    src: mFourteen,
    price: '1299.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Black',
    brand: 'Undercover',
    gender: 'men',
    key: '32',
  },
  {
    title: 'Face Long Sleeve',
    src: mFifteen,
    price: '699.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    type: 'Top',
    color: 'Red',
    brand: 'Yohji Yamamoto',
    gender: 'men',
    key: '33',
  },
];

export default cards;
