const cards = [
  {
    title: 'Black Snake Dress',
    src: '/img/clothes/one.jpeg',
    price: '1849.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    key: '1',
    gender: 'woman',
    type: 'bottom',
    color: 'black',
  },
  {
    title: 'Tattered Silk Coat',
    src: '/img/clothes/two.jpeg',
    price: '1379.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    key: '2',
    gender: 'woman',
    type: 'shoes',
    color: 'grey',
  },
  {
    title: 'Royal Gold Gown',
    src: '/img/clothes/three.jpeg',
    price: '859.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    key: '3',
    gender: 'woman',
    type: 'top',
    color: 'blue',
  },
  {
    title: 'Fine Ripped Shirt',
    src: '/img/clothes/four.jpeg',
    price: '1319.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    key: '4',
    gender: 'woman',
    type: 'top',
    color: 'black',
  },
  {
    title: 'Renaissance Dress',
    src: '/img/clothes/five.jpeg',
    price: '2899.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    key: '5',
    gender: 'woman',
    type: 'top',
    color: 'white',
  },
  {
    title: 'Black Buttoned Overcoat',
    src: '/img/clothes/six.jpeg',
    price: '659.99',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    key: '6',
    gender: 'woman',
    type: 'top',
    color: 'black',
  },
  {
    title: 'Black Layered Top',
    src: '/img/clothes/seven.jpeg',
    price: '779.99',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    key: '7',
    gender: 'woman',
    type: 'top',
    color: 'black',
  },
];

export default cards;
